# Generated by Django 4.2 on 2023-05-21 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMensajeros', '0001_initial'),
        ('GestionClientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleClienteMensajeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionClientes.cliente')),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionMensajeros.mensajeros')),
            ],
        ),
    ]
