# Generated by Django 4.2 on 2023-05-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMensajeros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeros',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
