# Generated by Django 4.2 on 2023-05-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMensajeros', '0002_alter_mensajeros_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeros',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
