# Generated by Django 4.2 on 2023-05-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientes', '0001_initial'),
        ('GestionMensajeros', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='propietario_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionClientes.cliente'),
        ),
        migrations.AddField(
            model_name='user',
            name='propietario_mensajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMensajeros.mensajeros'),
        ),
    ]
