name: Prueba

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply database migrations
        run: python manage.py migrate --database=test

      - name: Load environment variables
        uses: ammaraskar/setup-dotenv@v1
        with:
          path: .env

      - name: Run tests
        run: |
          python manage.py test
